### PR TITLE
Ejh 20161202 annotator integration

### PR DESCRIPTION
**Pull request by ejhumphrey**
* Modifies the backend server to talk with the audio annotator front-end.
* Includes demo audio and script to run the machinery locally
* Tests updated
* Unclear if the annotator HTML will render correctly through pages, but we'll find out when this comes back to master.

**Note**: The audio-annotator submodule was updated in the course of these changes.

---
This change is [Reviewable](https://reviewable.io/reviews/cosmir/open-mic/36)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 13 of 16 files at r1.
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 60 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TQtPVztTOOe7-S-t:-KY5TQtQ3Whx1zd-IR__:bqn75ma) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/README.md#L60)):*
> ```Markdown
> This will start the backend server (CMS), upload a few audio files, and begin serving the audio annotation tool locally. By default this will appear at [http://localhost:8000/docs/annotator.html](http://localhost:8000/docs/annotator.html).
> 
> **Note**: For some reason, loading the audio seems to get "stuck" on occasion. To unblock it, manually proceed to an audio file's URL once the server is running, e.g. [http://localhost:8080/api/v0.1/audio/740c835f-a23d-41ef-b84c-0cd1de4edfa5](http://localhost:8080/api/v0.1/audio/740c835f-a23d-41ef-b84c-0cd1de4edfa5).
> ```

Is hard-coding this really useful? I imagine the hash could change, and break this link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 66 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5Tc1OQyA0GBpNhx8x:-KY5Tc1OQyA0GBpNhx8y:b-wtn5e9) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/README.md#L66)):*
> ```Markdown
> ### Content Management System
> 
> See the [ReadMe](https://github.com/cosmir/open-mic/blob/master/backend_server/README.md) for details on running the backend web server.
> ```

Can this link be relative?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Review status: 13 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KY5TpkAmFLMOtkltyU3:b-9qsedb) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
> ```Shell
> python backend_server/main.py --port 8080 --local --debug &
> CMS_PID=$!
> sleep 4s
> ```

This is okay for now, but this should really be a daemon that stores its PID to a user-specified pid file, which can be read once the initial process terminates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[README.md, line 60 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TQtPVztTOOe7-S-t:-KY5bOtmCNoOPv0arfW7:bxx3a40) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/README.md#L60)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Is hard-coding this really useful? I imagine the hash could change, and break this link.
</blockquote></details>

UUIDs are deterministic based on the bytestring of the file; this points to a checked in file, and shouldn't change. That said, it's worth mentioning that in the README to prevent future confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[README.md, line 66 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5Tc1OQyA0GBpNhx8x:-KY5bn8bTJHmCnI7Ngu1:b-om95x1) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/README.md#L66)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Can this link be relative?
</blockquote></details>

¯\_(ツ)_/¯ I'll look into it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KY5bq_ct4zLNQ5HbdTV:bqujhhs) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

This is okay for now, but this should really be a daemon that stores its PID to a user-specified pid file, which can be read once the initial process terminates.
</blockquote></details>

I spent 10-15 minutes rooting around the interstacks, and didn't find an example I like -- do you have one in mind you could point to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KY5ct89XTe43Oy0J3bi:b-8hdlp9) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
<details><summary><i>Previously, ejhumphrey (Eric J. Humphrey) wrote…</i></summary><blockquote>

I spent 10-15 minutes rooting around the interstacks, and didn't find an example I like -- do you have one in mind you could point to?
</blockquote></details>

How about start-stop-daemon?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KY5tzjJrauD-spe2Bkf:b-ewt5e0) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

How about start-stop-daemon?
</blockquote></details>

looks like that's linux only? suppose that would work for travis, but us OS X folks couldn't run it locally ... this is at least unix compliant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
Reviewed 2 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KYEPjllmp-VmLiBR7aU:bptfc8q) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
<details><summary><i>Previously, ejhumphrey (Eric J. Humphrey) wrote…</i></summary><blockquote>

looks like that's linux only? suppose that would work for travis, but us OS X folks couldn't run it locally ... this is at least unix compliant?
</blockquote></details>

Ugh, OSX.  See thread: https://apple.stackexchange.com/questions/99888/is-there-any-port-of-start-stop-daemon-for-os-x

I guess that works via `launchctl` or `launchd` or something, but I have no way to verify.  Sorry!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KZ7LC0T8CPys4C9sYBX:bxtv92j) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

Ugh, OSX.  See thread: https://apple.stackexchange.com/questions/99888/is-there-any-port-of-start-stop-daemon-for-os-x

I guess that works via `launchctl` or `launchd` or something, but I have no way to verify.  Sorry!
</blockquote></details>

Doesn't seem to be the answer -- might need to use a different process shell?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
@bmcfee can I get a fresh look on this? I swapped out the bash shell script demo in favor of a python version, which is probably (hopefully) preferable to the previous solution. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36#-:-KZTFcEA34-XEm3jWmS4:bikxuto)*

**Comment by ejhumphrey** [comment]
*[run_demo.sh, line 6 at r1](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KY5TpkAmFLMOtkltyU2:-KZTG1ytjyExQcY8havG:bft3bnf) ([raw file](https://github.com/cosmir/open-mic/blob/0804e6d60eaec580434a4ed0dec67d3f307c9078/run_demo.sh#L6)):*
<details><summary><i>Previously, ejhumphrey (Eric J. Humphrey) wrote…</i></summary><blockquote>

Doesn't seem to be the answer -- might need to use a different process shell?
</blockquote></details>

I've rm'ed this file in favor of `demo.py`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo.py, line 39 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXbiyvGf9cGahe9Qi-:-KZXbiyvGf9cGahe9Qi0:b2h0y68) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L39)):*
> ```Python
>     try:
>         input("Press return to exit.")
>     except:
> ```

don't do a bare catch here; use the correct exception class

---

*[demo.py, line 42 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXboKUyw8267DWgbg1:-KZXboKUyw8267DWgbg2:bkii870) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L42)):*
> ```Python
>         pass
>     os.killpg(os.getpgid(server.pid), signal.SIGTERM)
>     os.killpg(os.getpgid(webapp.pid), signal.SIGTERM)
> ```

put subprocess kills in a finally block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[demo.py, line 1 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXbws2s9ZvJ5br6oNa:-KZXbws2s9ZvJ5br6oNb:b-t3w8gk) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

use #!/usr/bin/env python instead of #!/usr/bin/python to ensure proper environment capsulization

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by bmcfee** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[demo.py, line 25 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXc3qg6MmIUvg558GH:-KZXc3qg6MmIUvg558GI:b-ws2is8) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L25)):*
> ```Python
>                                '8080', '--local', '--debug'],
>                               stdout=subprocess.PIPE, preexec_fn=os.setsid)
>     time.sleep(4)
> ```

this still seems wrong, but we can revisit later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[demo.py, line 1 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXbws2s9ZvJ5br6oNa:-KZY8ptK9gO7-dnB6s-6:b-896fix) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L1)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

use #!/usr/bin/env python instead of #!/usr/bin/python to ensure proper environment capsulization
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[demo.py, line 42 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXboKUyw8267DWgbg1:-KZYCve0Ix7dbhPqUJPd:b-896fix) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L42)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

put subprocess kills in a finally block
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[demo.py, line 25 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXc3qg6MmIUvg558GH:-KZYHaYVLCWBBTSwuUXD:b-sf2pg3) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L25)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

this still seems wrong, but we can revisit later.
</blockquote></details>

I did something smarter here, you might want to give this a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[demo.py, line 42 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXboKUyw8267DWgbg1:-KZYJKcATBKqVnIZxCic:b1re1l3) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L42)):*
<details><summary><i>Previously, ejhumphrey (Eric J. Humphrey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually, didn't need that second try / except? I was getting some funny business from `input()`, but it seems to have resolved itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
*[demo.py, line 39 at r3](https://reviewable.io:443/reviews/cosmir/open-mic/36#-KZXbiyvGf9cGahe9Qi-:-KZYJS-QOqtFonhdoxDG:b-jmjhc0) ([raw file](https://github.com/cosmir/open-mic/blob/9f0d61891efb195b3e5d31c324429482413e1643/demo.py#L39)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary><blockquote>

don't do a bare catch here; use the correct exception class
</blockquote></details>

unnec.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
Reviewed 1 of 2 files at r4.
Review status: 15 of 16 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
tiny ping @bmcfee

**Comment by bmcfee** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cosmir/open-mic/36)*

**Comment by ejhumphrey** [comment]
thanks, merging

**Pull request merged**
