### PR TITLE
Flask Framework

### PR DESCRIPTION
**Pull request by stefan-balke**
Alright, I started to fool around with flask and think that this might be a way to go. It's all open for discussion. Basically I was very much inspired by https://github.com/miguelgrinberg/flasky/tree/7a and cleaned it up (although most of the things will be back in later I suppose). However, the API is currently not running and I will use this PR to keep you up to date and incorporate some feedback.

---

This change is [Reviewable](https://reviewable.io/reviews/cosmir/open-mic/22)

### CODE REVIEW

**Comment by ejhumphrey** [comment]
looks interesting! can I trouble you for a bit more context? by my read of it, it seems like the `flasky` approach is a clean way of deploying to different environments, e.g. dev, prod .. have I got the right of it?

relevant to #23, any idea if this approach is compatible with [app engine deployment](https://github.com/GoogleCloudPlatform/appengine-flask-skeleton)?

**Comment by ejhumphrey** [comment]
will resolve #11

**Comment by stefan-balke** [comment]
> by my read of it, it seems like the flasky approach is a clean way of deploying to different environments, e.g. dev, prod .. have I got the right of it?

No, it's more a way of decentralizing the `main.app`. Basically it's mimicking "the Django approach" of having different files for different views etc.
In this context you have a folder for each category of views (e.g., all views concerning annotations go into the folder `annotations`). This is what flask calls blueprints.
Those blueprints are then registered in the main file `backend_server/app/__init__.py` which puts it all together.

All in all, my hope is, that it makes the app easier to maintain.

**Comment by stefan-balke** [comment]
> relevant to #23, any idea if this approach is compatible with app engine deployment?

Not yet, but I guess since it stays a flask app, this won't be a problem.

**Comment by ejhumphrey** [comment]
cool, I'm all for easier to maintain! 😉 

before investing too much time & effort, we should investigate / test whether or not (and if so, how) a decentralized flask app can be deployed on App Engine. Based on the proposed architecture I spec'ed out, the backend service shouldn't be more than a few hundred lines of Python in year 1 (and doesn't need any resources or templates, e.g. HTML / CSS) ... so a small monolithic flask app wouldn't be the worst thing (whereas managing a cluster might be).

**Comment by stefan-balke** [comment]
> the backend service shouldn't be more than a few hundred lines of Python in year 1 (and doesn't need any resources or templates, e.g. HTML / CSS) ... so a small monolithic flask app wouldn't be the worst thing (whereas managing a cluster might be).

Oh, then this is totally not the right thing to do. I thought all the management of the annotations, the annotation process itself should be handled by this.

When I understand you correctly, the plan is to have a backend API which only "RESTs" the data and accessing the data web-based is another story?

**Comment by ejhumphrey** [comment]
> the plan is to have a backend API which only "RESTs" the data and accessing the data web-based is another story?

yep! The architecture I proposed is below, with the flask backend server in green:

screenshot 2016-10-14 14 54 53

As I've pictured it, the web annotator could be served separately, run locally, etc ... I wanted to separate the two efforts in the repository so that, by defining the RESTful API, two teams could work on their respective parts independently. 

Is that a good and reasonable plan? Would gladly admit to any oversights.

**Comment by stefan-balke** [comment]
> Is that a good and reasonable plan? Would gladly admit to any oversights.

No, LGTM. I'd like to see the REST-API versioned, in the case this will be opened up to other projects. However, should the "Annotation Web App" also live in this repo? Then I could use some of the work I've already done for that frontend.

**Comment by stefan-balke** [comment]
Alright, last questions for today:
Should the front end be also a Flask app or pure javascript. If so, something like AngularJS or ember? I guess Flask would be the easiest although "hardest" to deploy?

**Comment by ejhumphrey** [comment]
great call on versioning! will add that ... somewhere... 

As for the web annotation machinery, I was imagining that would be pure javascript / HTML / CSS that gets served off some kind of scalable hosting, e.g. github pages.

And, actually, in about 90 seconds, I've figured out how to set this repository up with github pages: https://cosmir.github.io/open-mic/

Based on my limited understanding of things, this might be an excellent delivery mechanism for our web-facing tooling. We can have the annotator, an about page, all that good stuff, running directly out of the repository ... will reference this in #8.

**Comment by julian-urbano** [comment]
If we use github pages, please keep this under https://cosmir.github.io/open-mic/somewhere/down/here so that we can use the root for an actual website with all the info about the challenge.

**Comment by ejhumphrey** [comment]
yea, I think we're saying the same thing ... I'm proposing that https://cosmir.github.io/open-mic/ be a proper landing page with an about and all that jazz, but you could also login and navigate to annotation through it (https://cosmir.github.io/open-mic/annotate) ... expanded in #24.

**Comment by ejhumphrey** [comment]
@stefan-balke what are your thoughts re: actions on this PR?

**Comment by stefan-balke** [comment]
Well, I still like making the backend more modular, at least the endpoints for the API.

Concerning this PR:
It's now too off from the HEAD so, we can close this out and I'll eventually propose something new when the backend stabilizes...

**Pull request closed without merging**
